printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: always
singleAttributePerLine: false

plugins:
  - '@ianvs/prettier-plugin-sort-imports'

# prettier-plugin-sort-imports
importOrder:
  - '<BUILTIN_MODULES>'
  - ''
  - '<THIRD_PARTY_MODULES>'
  - ''
  - '^~/'
  - ''
  - '^/'
  - '^\.\./'
  - '^\./'
importOrderTypeScriptVersion: '5.8.0'
