import type { GadgetListMeta } from '@/tools/gadget/types'

export default [
	{ type: 'h2', text: 'user' },
	'Logout-confirm',
	'Navigation_popups',
	'ShowAvatar',
	'UserAvatar',
	'MarkRights',
	'Purge',
	'RandomSong',
	'editCount',
	'mwPanel',
	'shortlink',
	'noteTA',
	{ type: 'h2', text: 'skin' },
	'sidebarHidden',
	'colorLinks',
	'SideBarPic',
	'text-autospace',
	'text-spacing-trim',
	'userpagecat',
	{ type: 'h2', text: 'edit' },
	'moesync',
	'Cat-a-lot',
	'HotCat',
	'InPageEdit',
	'InPageEdit-NEXT',
	'Wikiplus',
	'Wikiplus-highlight',
	{ type: 'h2', text: 'interface' },
	'allmessageFilter',
	'interfaceVariantConverter',
	{ type: 'h2', text: 'admin' },
	'rollback-summary',
	'MarkAsResolved',
	'registerToDelete',
	'CleanDeleteReasons',
	'deletion',
	{ type: 'h2', text: 'system' },
	'site-js',
	'site-lib',
	'site-styles',
	'LocalObjectStorage',
	'libOOUIDialog',
	'libPolyfill',
	'libCachedCode',
	'libDiscussionUtil',
] satisfies GadgetListMeta
